---
database:
  hostname: localhost
  database: "thekingsbury"
  username: root
  password: "123"
  port: 3306
dumps:
  dirname: db
binaries:
  mysql: "/usr/bin/mysql"
  git: "/usr/bin/git"
directory:
  db: "/var/www/wp-db-backup/db"